const fs = require('fs');
const path = require('path');

const LUCIDE = path.join(__dirname, '..', 'node_modules', 'lucide-static', 'icons');
const TABLER = path.join(__dirname, '..', 'node_modules', '@tabler', 'icons', 'icons', 'outline');
const SVG = path.join(__dirname, '..', 'svg');

const PALETTES = {
  '01-devices': { bg: '#eff6ff', grad: [['#2563eb','#60a5fa'],['#1e40af','#60a5fa']], accent: ['#475569','#94a3b8','#2563eb','#60a5fa','#1e40af'] },
  '02-physical-computing': { bg: '#f0fdf4', grad: [['#16a34a','#4ade80'],['#15803d','#86efac']], accent: ['#fbbf24','#ea580c','#16a34a','#4ade80','#15803d'] },
  '03-programming': { bg: '#f0fdf4', grad: [['#16a34a','#4ade80'],['#15803d','#a3e635']], accent: ['#facc15','#16a34a','#4ade80','#15803d','#a3e635'] },
  '04-algorithm': { bg: '#ecfeff', grad: [['#0891b2','#22d3ee'],['#155e75','#06b6d4']], accent: ['#0891b2','#06b6d4','#22d3ee','#155e75','#67e8f9'] },
  '05-network-security': { bg: '#fef2f2', grad: [['#dc2626','#f87171'],['#2563eb','#60a5fa']], accent: ['#fbbf24','#dc2626','#2563eb','#f87171','#60a5fa'] },
  '06-data-ai': { bg: '#eff6ff', grad: [['#2563eb','#8b5cf6'],['#06b6d4','#10b981']], accent: ['#f59e0b','#2563eb','#8b5cf6','#06b6d4','#10b981'] },
  '07-design-thinking': { bg: '#fdf2f8', grad: [['#ec4899','#f472b6'],['#8b5cf6','#a78bfa']], accent: ['#fbbf24','#ec4899','#8b5cf6','#f472b6','#a78bfa'] },
  '08-steam': { bg: '#fff7ed', grad: [['#ea580c','#fb923c'],['#f59e0b','#fbbf24']], accent: ['#16a34a','#ea580c','#fb923c','#f59e0b','#fbbf24'] },
  '09-teaching': { bg: '#ecfeff', grad: [['#0891b2','#22d3ee'],['#f59e0b','#fbbf24']], accent: ['#16a34a','#0891b2','#22d3ee','#f59e0b','#fbbf24'] },
  '10-visual-symbols': { bg: '#f8fafc', grad: [['#1e293b','#475569'],['#2563eb','#60a5fa']], accent: ['#dc2626','#16a34a','#1e293b','#2563eb','#475569'] },
  '11-numbers': { bg: '#fef3c7', grad: [['#d97706','#f59e0b'],['#b45309','#fbbf24']], accent: ['#92400e','#d97706','#f59e0b','#fbbf24','#b45309'] },
  '12-shapes': { bg: '#fae8ff', grad: [['#9333ea','#c084fc'],['#7e22ce','#a855f7']], accent: ['#6b21a8','#9333ea','#c084fc','#a855f7','#7e22ce'] },
};

// [lucide-icon-name, output-filename, 한국어이름, 설명, 사용상황]
const ICONS = {
'01-devices': [
['monitor','monitor','모니터','컴퓨터 모니터 화면','컴퓨터 구성요소 설명, 출력장치 소개'],
['laptop','laptop','노트북','휴대용 노트북 컴퓨터','정보기기 종류, 모바일 컴퓨팅'],
['tablet','tablet','태블릿','태블릿 PC','터치 기반 기기, 모바일 학습'],
['smartphone','smartphone','스마트폰','스마트폰 기기','모바일 기기, 앱 개발'],
['computer','desktop','데스크톱','데스크톱 컴퓨터','컴퓨터 구성, 하드웨어 수업'],
['keyboard','keyboard','키보드','입력 장치 키보드','입력장치, 타이핑 수업'],
['mouse','mouse','마우스','컴퓨터 마우스','입력장치, 인터페이스'],
['printer','printer','프린터','문서 출력 프린터','출력장치, 주변기기'],
['webcam','webcam','웹캠','화상 카메라','영상 입력, 화상 수업'],
['mic','microphone','마이크','음성 입력 마이크','입력장치, 음성 인식'],
['speaker','speaker','스피커','음향 출력 스피커','출력장치, 멀티미디어'],
['headphones','headphones','헤드폰','음향 헤드폰','출력장치, 개인 학습'],
['cpu','cpu','CPU','중앙처리장치','컴퓨터 구조, 프로세서 설명'],
['hard-drive','hard-drive','하드드라이브','저장장치','보조기억장치, 데이터 저장'],
['memory-stick','memory-stick','메모리','메모리 스틱','기억장치, 저장매체'],
['usb','usb','USB','USB 연결단자','인터페이스, 데이터 전송'],
['server','server','서버','네트워크 서버','서버 개념, 클라이언트-서버'],
['router','router','라우터','네트워크 라우터','네트워크 장비, 인터넷 연결'],
['camera','camera','카메라','디지털 카메라','영상 입력, 멀티미디어'],
['battery','battery','배터리','전원 배터리','전원 공급, IoT 기기'],
['bluetooth','bluetooth','블루투스','블루투스 무선통신','무선 통신, 근거리 통신'],
['wifi','wifi','와이파이','무선 인터넷','무선 네트워크, 인터넷 연결'],
['tv','tv','TV','텔레비전 화면','디스플레이, 출력장치'],
['smartphone-charging','smartphone-charging','충전','기기 충전','전원 관리, 배터리'],
['gamepad-2','gamepad','게임패드','게임 컨트롤러','입력장치, 게임 개발'],
['radio','radio','라디오','라디오 수신기','통신 기기, 아날로그/디지털'],
['disc','disc','디스크','저장 디스크','광학 저장매체, CD/DVD'],
['watch','smartwatch','스마트워치','스마트 시계','웨어러블 기기, IoT'],
['signal','signal','신호','통신 신호','신호 전송, 네트워크 상태'],
['antenna','antenna','안테나','무선 안테나','통신 장비, 신호 수신'],
['plug','plug','플러그','전원 플러그','전원 연결, 인터페이스'],
['cable','cable','케이블','연결 케이블','유선 연결, 데이터 전송'],
['ethernet-port','ethernet','이더넷','이더넷 포트','유선 네트워크, LAN'],
['hdmi-port','hdmi','HDMI','HDMI 포트','영상 출력, 인터페이스'],
['projector','projector','프로젝터','영상 프로젝터','출력장치, 프레젠테이션'],
['scan-line','scan','스캐너','문서 스캐너','입력장치, 문서 디지털화'],
['drone','drone','드론','무인 항공기','IoT, 로봇 기술'],
['satellite-dish','satellite-dish','위성안테나','위성 수신 안테나','통신, 위성 기술'],
['gpu','gpu','GPU','그래픽처리장치','병렬처리, AI 연산'],
['circuit-board','circuit-board','회로기판','전자 회로기판','하드웨어 구조, 전자공학'],
['nfc','nfc','NFC','근거리 무선통신','모바일 결제, 태그 인식'],
['laptop-minimal','laptop-mini','미니노트북','경량 노트북','모바일 컴퓨팅, 크롬북'],
['monitor-smartphone','monitor-phone','모니터+폰','모니터와 스마트폰 연결','반응형 디자인, 미러링'],
['power','power-on','전원켜기','전원 버튼','시스템 시작, 전원 관리'],
['power-off','power-off','전원끄기','전원 종료 버튼','시스템 종료, 절전'],
['screen-share','screen-share','화면공유','화면 공유 기능','원격 수업, 화면 미러링'],
['headset','headset','헤드셋','마이크 헤드셋','화상 수업, 음성 통화'],
['scan-face','face-scan','얼굴인식','얼굴 스캔 인식','생체인증, AI 인식'],
['scan-barcode','barcode-scan','바코드스캔','바코드 읽기','자동 인식, 물류 관리'],
['tablet-smartphone','tablet-phone','태블릿+폰','태블릿과 스마트폰','모바일 기기 비교, 크기'],
['joystick','joystick','조이스틱','게임 조이스틱','입력장치, 로봇 제어'],
['navigation-2','navigation','내비게이션','길 안내 장치','GPS, 위치 서비스'],
['vibrate','vibrate','진동','진동 알림','햅틱 피드백, 모바일 알림'],
['tower-control','control-tower','관제탑','통신 관제탑','통신 관제, IoT 허브'],
['radio-receiver','radio-receiver','수신기','라디오 수신 장치','방송 수신, 아날로그 통신'],
['lamp-desk','desk-lamp','탁상등','책상 조명','스마트 조명, IoT 기기'],
['monitor-play','monitor-play','미디어모니터','영상 재생 모니터','미디어 재생, 디지털 사이니지'],
['app-window','app-window','앱화면','응용프로그램 창','소프트웨어, 앱 인터페이스'],
['clapperboard','clapperboard','클래퍼보드','영상 촬영 도구','영상 제작, 미디어'],
['fingerprint-pattern','fingerprint2','지문패턴','지문 인식 패턴','생체인식, 보안 인증'],
],
'02-physical-computing': [
['cpu','microcontroller','마이크로컨트롤러','소형 제어 장치','아두이노, 피지컬컴퓨팅 기초'],
['circuit-board','circuit','회로','전자 회로','회로 설계, 전자공학 기초'],
['lightbulb','led','LED','발광 다이오드','출력 소자, 디지털 출력'],
['thermometer','temp-sensor','온도센서','온도 측정 센서','센서 입력, 환경 모니터링'],
['sun','light-sensor','빛센서','조도 센서','아날로그 입력, 환경 감지'],
['activity','pulse-sensor','펄스센서','심박 센서','바이오 센서, 건강 모니터링'],
['radar','ultrasonic','초음파센서','거리 측정 센서','거리 측정, 로봇 제어'],
['volume-2','buzzer','부저','소리 출력 부저','디지털 출력, 알림'],
['rotate-cw','servo-motor','서보모터','각도 제어 모터','모터 제어, 로봇 관절'],
['circuit-motor','dc-motor','DC모터','직류 모터','모터 구동, 바퀴 제어'],
['toggle-right','switch','스위치','온오프 스위치','디지털 입력, 토글'],
['sliders','potentiometer','가변저항','가변 저항기','아날로그 입력, 값 조절'],
['zap','relay','릴레이','전자 릴레이','고전압 제어, 스위칭'],
['monitor','lcd','LCD','액정 디스플레이','출력 장치, 정보 표시'],
['grid-3x3','led-matrix','LED매트릭스','LED 배열판','출력, 패턴 표시'],
['cable','jumper-wire','점퍼와이어','연결 전선','회로 연결, 브레드보드'],
['battery','battery-pack','배터리팩','전원 공급','전원, 이동형 프로젝트'],
['sun','solar-panel','태양전지판','태양광 패널','신재생 에너지, 친환경'],
['gauge','multimeter','멀티미터','전기 측정기','전압/전류 측정, 디버깅'],
['bot','robot','로봇','자율 로봇','로봇공학, 자동화'],
['car','robot-car','로봇카','바퀴 달린 로봇','이동 로봇, 자율주행'],
['radio-tower','rf-module','RF모듈','무선 통신 모듈','무선 통신, IoT'],
['bluetooth','ble-module','BLE모듈','저전력 블루투스','근거리 무선, 웨어러블'],
['wifi','wifi-module','와이파이모듈','WiFi 통신 모듈','인터넷 연결, IoT'],
['map-pin','gps','GPS모듈','위치 추적 모듈','위치 기반, 내비게이션'],
['scan','rfid','RFID','무선 식별 태그','식별, 출입 관리'],
['cog','gear','기어','동력 전달 기어','기계 요소, 로봇 구조'],
['droplets','humidity-sensor','습도센서','습도 측정 센서','환경 모니터링, 스마트팜'],
['wind','fan-module','팬모듈','냉각 팬','온도 제어, 출력'],
['speaker','piezo','피에조','피에조 소자','소리 출력/감지, 진동'],
['circuit-ammeter','ammeter','전류계','전류 측정기','전류 측정, 회로 분석'],
['circuit-battery','circuit-battery','전지기호','회로 전원 기호','회로도, 전원 표시'],
['circuit-diode','diode','다이오드','단방향 소자','전자부품, 회로'],
['circuit-resistor','resistor','저항','저항 소자','전자부품, 옴의 법칙'],
['circuit-capacitor','capacitor','축전기','에너지 저장 소자','전자부품, 충방전'],
['robot','robot-tabler','로봇','자율 로봇','로봇공학, 피지컬컴퓨팅'],
['device-cctv','cctv','CCTV','영상 감시 카메라','IoT, 보안 시스템'],
['cpu-2','processor','프로세서','연산 장치','마이크로프로세서, 연산'],
['microchip','microchip','마이크로칩','집적 회로 칩','피지컬컴퓨팅, 마이크로프로세서'],
['logic-and','logic-and','AND게이트','논리곱 게이트','논리회로, 디지털 논리'],
['logic-or','logic-or','OR게이트','논리합 게이트','논리회로, 디지털 논리'],
['logic-not','logic-not','NOT게이트','부정 게이트','논리회로, 반전'],
['logic-xor','logic-xor','XOR게이트','배타적 논리합','논리회로, 암호화'],
['logic-nand','logic-nand','NAND게이트','부정 논리곱','범용 게이트, 논리회로'],
['logic-nor','logic-nor','NOR게이트','부정 논리합','범용 게이트, 논리회로'],
['logic-buffer','logic-buffer','버퍼게이트','신호 증폭 버퍼','신호 처리, 논리회로'],
['propeller','propeller','프로펠러','회전 프로펠러','드론, 팬 모듈'],
['magnet','magnet-sensor','자석','자기력 센서','홀센서, 자기장 감지'],
['orbit','orbit','궤도','회전 궤도','모터 회전, 자이로스코프'],
['signal-high','signal-high','강한신호','높은 신호 세기','센서 출력, 통신 품질'],
['signal-low','signal-low','약한신호','낮은 신호 세기','센서 민감도, 통신 거���'],
['scale-3d','scale-3d','3축센서','3축 측정 센서','가속도센서, 자이로'],
['scan-barcode','barcode-sensor','바코드센서','바코드 읽기 모듈','자동 인식, 재고 관리'],
],
'03-programming': [
['variable','variable','변수','데이터 저장 변수','변수 개념, 데이터 타입'],
['function-square','function','함수','코드 함수','함수 정의, 코드 재사용'],
['repeat','loop','반복문','반복 실행 구조','for/while 루프, 반복'],
['iteration-cw','for-loop','FOR반복','횟수 반복문','for문, 카운터 반복'],
['refresh-cw','while-loop','WHILE반복','조건 반복문','while문, 조건 반복'],
['list','array','배열','순서 있는 데이터 목록','배열, 리스트 자료형'],
['type','string','문자열','텍스트 데이터','문자열 처리, 텍스트'],
['hash','integer','정수','정수 데이터 타입','숫자 자료형, 연산'],
['toggle-left','boolean','불리언','참/거짓 값','논리값, 조건 판단'],
['braces','code-block','코드블록','중괄호 코드 블록','코드 구조, 범위'],
['brackets','brackets','대괄호','배열/인덱스 접근','배열 접근, 인덱싱'],
['parentheses','parentheses','소괄호','함수 호출 괄호','함수 호출, 연산 순서'],
['indent-increase','indent','들여쓰기','코드 들여쓰기','코드 구조, 가독성'],
['message-square','comment','주석','코드 설명 주석','코드 설명, 문서화'],
['terminal','terminal','터미널','명령줄 인터페이스','CLI, 명령어 실행'],
['square-terminal','console','콘솔','출력 콘솔','디버깅, 출력 확인'],
['code','code','코드','프로그래밍 코드','코딩, 소스코드'],
['code-xml','html','HTML','웹 마크업 언어','웹 개발, 문서 구조'],
['palette','css','CSS','웹 스타일 언어','웹 디자인, 스타일링'],
['file-json','json','JSON','데이터 교환 형식','데이터 형식, API'],
['bug','bug','버그','프로그램 오류','디버깅, 오류 수정'],
['bug-off','debug','디버그','오류 수정 과정','디버깅 기법, 문제해결'],
['circle-stop','breakpoint','중단점','실행 중단 지점','디버깅, 단계 실행'],
['alert-triangle','error','에러','오류 발생','에러 처리, 예외'],
['alert-circle','warning','경고','경고 메시지','경고 처리, 코드 품질'],
['git-commit','git-commit','커밋','버전 저장 단위','버전관리, 변경 기록'],
['git-branch','git-branch','브랜치','코드 가지','버전관리, 병렬 개발'],
['git-merge','git-merge','머지','코드 병합','버전관리, 협업'],
['git-pull-request','pull-request','풀리퀘스트','코드 검토 요청','협업, 코드리뷰'],
['blocks','block-coding','블록코딩','블록 기반 코딩','스크래치, 엔트리'],
['toy-brick','scratch-block','스크래치블록','스크래치 코딩 블록','블록코딩, 초등 SW교육'],
['play','run','실행','프로그램 실행','코드 실행, 테스트'],
['square','stop','정지','실행 중지','프로그램 종료, 중단'],
['log-in','input','입력','데이터 입력','input 함수, 사용자 입력'],
['log-out','output','출력','데이터 출력','print 함수, 결과 출력'],
['plus','operator-plus','덧셈연산','더하기 연산자','산술 연산, 수학'],
['minus','operator-minus','뺄셈연산','빼기 연산���','산술 연산, 수학'],
['x','operator-multiply','곱셈연산','곱하기 연산자','산술 연산, 수학'],
['divide','operator-divide','나눗셈연산','나누기 연산자','산술 연산, 수학'],
['equal','comparison','비교연산','비교 연산자','조건 비교, 논리'],
['package','module','모듈','코드 모듈','모듈화, 패키지'],
['library-big','library','라이브러리','코드 라이브러리','외부 라이브러리, import'],
['box','class','클래스','객체지향 클래스','OOP, 객체 설계'],
['component','object','객체','프로그래밍 객체','OOP, 인스턴스'],
['arrow-right','return','반환','함수 반환값','return문, 결과값'],
['shield','try-catch','예외처리','에러 처리 구문','try-catch, 안전한 코드'],
['file-code','source-code','소스코드','프로그램 소스','코드 작성, 파일'],
['rocket','deploy','배포','프로그램 배포','서비스 배포, 릴리스'],
['test-tube','testing','테스트','코드 테스트','단위 테스트, 품질'],
['clipboard-check','code-review','코드리뷰','코드 검토','협업, 품질 관리'],
['file-text','readme','리드미','프로젝트 설명서','문서화, 프로젝트 소개'],
['database','database','데이터베이스','데이터 저장소','DB, 데이터 관리'],
['table','sql','SQL','데이터 조회 언어','데이터베이스, 쿼리'],
['layout-dashboard','ide','IDE','통합개발환경','코드 에디터, 개발도구'],
['container','docker','컨테이너','가상화 컨테이너','배포, 환경 관리'],
['globe','web-dev','웹개발','웹 프로그래밍','웹사이트, 풀스택'],
['smartphone','app-dev','앱개발','모바일 앱 개발','앱 프로그래밍, 모바일'],
['workflow','algorithm-code','알고리즘','문제 해결 절차','알고리즘 설계, 효율성'],
['app-window','app-window','앱창','응용프로그램 창','GUI, 윈도우 프로그래밍'],
['square-code','square-code','코드박스','코드 입력 영역','코드 에디터, 입력 영역'],
['square-function','square-func','함수박스','함수 표현 상자','함수 정의, 수학 함수'],
['square-stack','stack-code','스택코드','코드 스택','호출 스택, 실행 컨텍스트'],
['notebook-text','notebook-code','코딩노트','코딩 학습 노트','학습 기록, 코딩 일지'],
['pencil-ruler','pencil-ruler','연필+자','설계 도구','코드 설계, 구조 기획'],
['milestone','milestone','마일스톤','프로젝트 이정표','개발 진행, 릴리스'],
['kanban','kanban','칸반보드','작업 관리판','애자일, 프로젝트 관리'],
['gantt-chart','gantt-chart','간트차트','일정 차트','프로젝트 일정, 계획'],
['ungroup','ungroup','분리','코드 분리','모듈 분리, 리팩토링'],
['group','group-code','그룹화','코드 그룹화','모듈화, 네임스페이스'],
['file-code-2','file-code-2','코드파일2','프로그래밍 파일','소스코드, 스크립트'],
['file-search','file-search','파일검색','파일 찾기','코드 검색, IDE 기능'],
['folder-tree','folder-tree','폴더트리','폴더 구조','프로젝트 구조, 디렉토리'],
['file-type-2','file-type','파일타입','파일 형식','확장자, 파일 종류'],
['binary','binary-code','이진코드','2진법 코드','비트, 디지털 표현'],
['book-open-text','book-docs','문서','개발 문서','API 문서, 매뉴얼'],
['book-marked','book-ref','참조문서','참고 자료','레퍼런스, 가이드'],
['brand-python','python','파이썬','파이썬 언어','파이썬 프로그래밍, AI'],
['brand-javascript','javascript','자바스크립트','JS 언어','웹 프로그래밍, 프론트엔드'],
['brand-html5','html5','HTML5','웹 마크업 5','웹 표준, 시맨틱 태그'],
['brand-css3','css3','CSS3','웹 스타일 3','웹 디자인, 애니메이션'],
['brand-react','react','리액트','리액트 프레임워크','컴포넌트, SPA'],
['brand-github','github','깃허브','코드 공유 플랫폼','버전관리, 협업'],
['brand-vscode','vscode','VS코드','코드 에디터','IDE, 개발환경'],
],
'04-algorithm': [
['workflow','flowchart','플로차트','순서도','알고리즘 표현, 프로그램 설계'],
['diamond','decision','판단기호','조건 판단 기호','순서도, 분기'],
['square','process','처리기호','처리 과정 기호','순서도, 연산'],
['circle','terminal-symbol','단말기호','시작/끝 기호','순서도, 흐름 시작과 끝'],
['arrow-down','flow-arrow','흐름화살표','실행 흐름 방향','순서도, 연결'],
['arrows-sort','sorting','정렬','데이터 정렬','정렬 알고리즘, 순서 배열'],
['search','linear-search','선형탐색','순차적 검색','기초 탐색, 순서대로'],
['stack-2','stack','스택','후입선출 자료구조','LIFO, 함수 호출'],
['link','linked-list','연결리스트','노드 연결 구조','동적 자료구조, 포인터'],
['binary-tree','binary-tree','이진트리','이진 트리 구조','트리 탐색, 계층 구조'],
['graph','graph','그래프','노드와 간선 구조','네트워크, 관계 표현'],
['topology-star-ring','bfs','너비우선탐색','BFS 탐색','그래프 탐색, 최단경로'],
['route','shortest-path','최단경로','최단 거리 탐색','다익스트라, 경로 찾기'],
['split','divide-conquer','분할정복','분할 후 해결','재귀, 큰 문제 분할'],
['undo','backtracking','백트래킹','되돌아가며 탐색','탐색, 조합 문제'],
['clock','time-complexity','시간복잡도','실행 시간 분석','효율성, Big-O'],
['hard-drive','space-complexity','공간복잡도','메모리 사용 분석','메모리 효율, Big-O'],
['repeat','recursion','재귀','자기 호출 구조','재귀 함수, 분할정복'],
['arrow-left-right','swap','교환','값 교환 연산','정렬, 자리 바꾸기'],
['list','array-index','배열인덱스','배열 위치 접근','인덱싱, 자료 접근'],
['shuffle','random','무작위','랜덤 선택','난수 생성, 확률'],
['target','optimization','최적화','최적 해 탐색','효율성 개선, 성능'],
['puzzle','problem-solving','문제해결','알고리즘적 사고','컴퓨팅 사고력, 분석'],
['brain','computational','컴퓨팅사고','컴퓨팅 사고력','추상화, 패턴인식'],
['sigma','summation','합계','시그마 합산','누적 합, 수열의 합'],
['binary','binary-num','이진수','2진법 숫자','진법 변환, 디지털'],
['hierarchy','hierarchy','계층구조','계층적 구조','트리 구조, 조직도'],
['hierarchy-2','hierarchy-2','계층도2','다단계 계층','다단계 분류, 상속'],
['topology-bus','topology-bus','버스토폴로지','일렬 연결 구조','네트워크 구조, 버스형'],
['topology-ring','topology-ring','링토폴로지','원형 연결 구조','네트워크 구조, 링형'],
['topology-star','topology-star','스타토폴로지','별형 연결 구조','네트워크 구조, 스타형'],
['topology-full','topology-full','메시토폴로지','완전 연결 구조','네트워크 구조, 메시형'],
['math-symbols','math-symbols','수학기호','수학 연산 기호','수학, 연산자'],
['math-function','math-function','수학함수','수학 함수 표현','함수, 입출력 관계'],
['math-integral','math-integral','적분','적분 기호','미적분, 면적 계산'],
['math-avg','math-avg','평균','산술 평균','통계, 중심경향'],
['math-1-divide-2','math-fraction','분수','분수 표현','분수, 나눗셈'],
['vector-bezier','bezier-curve','베지어곡선','곡선 보간','그래픽, 곡선 표현'],
['abacus','abacus','주판','수 계산 도구','고대 계산기, 수 세기'],
['math-greater','comparison-gt','크다비교','크다 비교연산','비교 연산, 부등호'],
['math-lower','comparison-lt','작다비교','작다 비교연산','비교 연산, 부등호'],
['math-x-plus-y','math-add','수식덧셈','변수 덧셈','수식, 변수 연산'],
['math-x-minus-y','math-sub','수식뺄셈','변수 뺄셈','수식, 변수 연산'],
['math-x-divide-y','math-div','수식나눗셈','변수 나눗셈','수식, 변수 연산'],
['git-commit','topological-sort','위상정렬','선행 관계 정렬','DAG, 작업 순서'],
['map','dijkstra','다익스트라','최단 경로 알고리즘','가중 그래프, 최단 거리'],
['compass','bellman-ford','벨만포드','음수 간선 최단경로','음수 가중치, 사이클 감지'],
['grid-2x2','matrix-algo','행렬','2차원 배열 구조','행렬 연산, 인접 행렬'],
['trees','spanning-tree','신장트리','최소 비용 연결','프림, 크루스칼 알고리즘'],
['circle-dot','set-structure','집합','집합 자료구조','합집합, 교집합, 중복 제거'],
['grip-horizontal','sliding-window','슬라이딩윈도우','구간 탐색 기법','부분 배열, 최적 구간'],
['move-horizontal','two-pointers','투포인터','양쪽 포인터 탐색','정렬 배열, 합 문제'],
['database','memoization','메모이제이션','결과 저장 기법','중복 계산 방지, DP 최적화'],
['scissors','pruning','가지치기','불필요 탐색 제거','탐색 최적화, 알파베타'],
['list-ordered','counting-sort','카운팅정렬','빈도 기반 정렬','비교 없는 정렬, 정수 정렬'],
['triangle','heap-sort','힙정렬','힙 기반 정렬','효율적 정렬, 우선순위'],
['scan','trie','트라이','문자열 검색 트리','문자열 탐색, 자동완성'],
['lock','mutex','뮤텍스','상호배제 잠금','동시성, 병렬 처리'],
['repeat-2','iteration-algo','반복순회','순회 반복 처리','이터레이션, 반복 접근'],
['percent','probability-algo','확률알고리즘','확률적 접근법','몬테카를로, 라빈카프'],
['link-2','double-linked','이중연결리스트','양방향 노드 연결','양방향 탐색, 삽입/삭제'],
['clipboard','lru-cache','LRU캐시','최근 사용 캐시','캐시 교체, 페이지 교체'],
['waypoints','kruskal','크루스칼','최소 신장 트리','MST, 간선 기반'],
['bar-chart-2','sort-visualization','정렬시각화','정렬 과정 표현','정렬 비교, 단계 시각화'],
],
'05-network-security': [
['globe','internet','인터넷','글로벌 네트워크','인터넷 개념, 월드와이드웹'],
['wifi','wifi-network','와이파이','무선 네트워크','무선 인터넷, 접속'],
['ethernet-port','ethernet','이더넷','유선 네트워크','LAN, 유선 연결'],
['router','router-net','라우터','패킷 경로 설정','네트워크 장비, 라우팅'],
['server','server-net','서버','서비스 제공 컴퓨터','클라이언트-서버, 호스팅'],
['cloud','cloud-net','클라우드','원격 컴퓨팅','클라우드 서비스, SaaS'],
['link','http','HTTP','웹 통신 프로토콜','웹 통신, 요청/응답'],
['link-2','url','URL','웹 주소','인터넷 주소 체계, 도메인'],
['at-sign','email','이메일','전자 우편','통신, 디지털 소통'],
['send','packet','패킷','데이터 전송 단위','네트워크 통신, 분할 전송'],
['gauge','bandwidth','대역폭','전송 용량','네트워크 속도, 성능'],
['clock','latency','지연시간','응답 지연','네트워크 성능, 속도'],
['chrome','browser','브라우저','웹 브라우저','인터넷 접속, 웹 탐색'],
['layout-dashboard','webpage','웹페이지','웹 문서','웹사이트, HTML'],
['cookie','cookie','쿠키','웹 쿠키 데이터','개인정보, 웹 추적'],
['database','cache','캐시','임시 저장소','성능 최적화, 저장'],
['shield','firewall','방화벽','네트워크 보안 장벽','보안, 접근 차단'],
['lock','encryption','암호화','데이터 암호화','정보 보호, 보안'],
['unlock','decryption','복호화','암호 해독','암호 해제, 키'],
['key','crypto-key','암호키','암호화 키','공개키/비밀키, 인증'],
['shield-check','ssl','SSL인증서','보안 인증서','HTTPS, 안전한 연결'],
['key-round','password','비밀번호','접근 비밀번호','인증, 보안 관리'],
['fingerprint','biometric','생체인증','생체 정보 인증','지문/얼굴 인식, 보안'],
['smartphone','two-factor','2단계인증','추가 인증 단계','보안 강화, OTP'],
['alert-triangle','phishing','피싱','사기 공격','사이버 보안, 예방'],
['bug','malware','악성코드','유해 프로그램','바이러스, 보안 위협'],
['shield-alert','ransomware','랜섬웨어','파일 암호화 공격','사이버 위협, 예방'],
['mail','spam','스팸','원치 않는 메시지','이메일 보안, 필터링'],
['eye-off','privacy','개인정보보호','개인정보 관리','디지털 시민, 프라이버시'],
['footprints','digital-footprint','디지털발자국','온라인 활동 흔적','디지털 시민, 온라인 윤리'],
['shield-x','cyber-attack','사이버공격','해킹 시도','보안 위협, 방어'],
['refresh-cw','update','보안업데이트','소프트웨어 갱신','보안 패치, 유지보수'],
['save','backup','백업','데이터 복사본','데이터 보호, 복구'],
['user-check','authentication','인증','사용자 확인','로그인, 신원 확인'],
['users','access-control','접근제어','권한 관리','역할 기반, 보안 정책'],
['scroll-text','audit-log','감사로그','활동 기록','모니터링, 보안 감사'],
['bell','alert','보안알림','위협 알림','모니터링, 사고 대응'],
['ban','block','차단','접근 차단','보안, 필터링'],
['qr-code','qr-code','QR코드','2차원 바코드','정보 인코딩, 인증'],
['network','network-topology','네트워크구조','네트워크 토폴로지','네트워크 설계, 구조'],
['globe-2','global-network','글로벌네트워크','세계 네트워크','국제 통신, 인터넷 백본'],
['globe-lock','secure-web','보안웹','보안 웹 접속','HTTPS, 안전한 브라우징'],
['earth','earth-net','지구본','지구 네트워크','글로벌 인터넷, WWW'],
['earth-lock','earth-secure','지구보안','지구 보안 연결','글로벌 보안, VPN'],
['cloud-download','cloud-download','클라우드다운','클라우드 다운로드','파일 내려받기, 동기화'],
['cloud-upload','cloud-upload','클라우드업로드','클라우드 업로드','파일 올리기, 백업'],
['cloud-off','cloud-off','클라우드오프','클라우드 해제','오프라인, 로컬 모드'],
['cloud-lightning','cloud-edge','엣지컴퓨팅','클라우드 엣지','에지 서버, 분산 처리'],
['server-cog','server-config','서버설정','서버 구성','서버 관리, 시스템 설정'],
['server-crash','server-error','서버오류','서버 장애','장애 대응, 복구'],
['database-backup','db-backup','DB백업','데이터베이스 백업','데이터 보호, 재해 복구'],
['database-zap','db-realtime','실시간DB','실시간 데이터베이스','실시간 동기화, Firebase'],
['rss','rss-feed','RSS피드','뉴스 피드','정보 구독, 콘텐츠 배포'],
['podcast','podcast','팟캐스트','음성 방송','미디어, 오디오 콘텐츠'],
['inbox','inbox','받은편지함','메일 수신함','이메일 관리, 메시지'],
['mail-check','mail-verified','인증메일','확인된 이메일','이메일 인증, 검증'],
['mail-open','mail-read','읽은메일','열린 이메일','메일 확인, 알림'],
['shield-half','half-shield','하프실드','절반 보호','부분 보안, 방어 수준'],
['shield-question','shield-unknown','보안질문','보안 확인 질문','보안 인증, 본인 확인'],
['shield-plus','shield-add','보안추가','보안 강화','추가 보안, 계층 방어'],
['scan-text','text-scan','텍스트스캔','문자 인식','OCR, 텍스트 추출'],
['handshake','handshake-net','핸드셰이크','통신 협상','프로토콜, TCP 핸드셰이크'],
],
'06-data-ai': [
['database','database-ai','데이터베이스','데이터 저장소','데이터 관리, 구조화'],
['table','spreadsheet','스프레드시트','표 형식 데이터','엑셀, 데이터 정리'],
['file-spreadsheet','csv','CSV파일','쉼표 구분 파일','데이터 교환, 표 형식'],
['chart-column','bar-chart','막대그래프','수직 막대 차트','데이터 비교, 시각화'],
['chart-line','line-chart','꺾은선그래프','시계열 차트','추세 분석, 시각화'],
['chart-pie','pie-chart','원그래프','비율 차트','구성비, 시각화'],
['chart-scatter','scatter-plot','산점도','상관 관계 차트','상관분석, 시각화'],
['chart-bar','histogram','히스토그램','도수 분포도','분포 분석, 통계'],
['chart-area','area-chart','영역그래프','누적 차트','추세, 시각화'],
['layout-dashboard','dashboard','대시보드','데이터 요약판','KPI, 모니터링'],
['filter','data-filter','데이터필터','조건별 추출','데이터 정제, 선별'],
['search','data-search','데이터검색','데이터 탐색','쿼리, 조건 검색'],
['trash-2','data-cleaning','데이터정제','오류 데이터 제거','전처리, 품질 향상'],
['alert-circle','outlier','이상치','비정상 데이터','이상 탐지, 통계'],
['sliders','normalization','정규화','데이터 스케일링','전처리, 표준화'],
['workflow','data-pipeline','데이터파이프라인','데이터 처리 흐름','ETL, 자동화'],
['clipboard-list','data-collection','데이터수집','데이터 모으기','설문, 관측, 크롤링'],
['file-question','survey','설문조사','데이터 수집 설문','1차 데이터, 조사'],
['globe','web-scraping','웹스크래핑','웹 데이터 수집','크롤링, 자동 수집'],
['plug','api-data','API데이터','API 통한 수집','데이터 연동, REST'],
['brain','neural-network','신경망','인공 신경망','딥러닝, AI 모델'],
['brain-circuit','deep-learning','딥러닝','심층 학습','CNN, RNN, 고급 AI'],
['brain-cog','machine-learning','머신러닝','기계 학습','지도학습, 비지도학습'],
['target','classification','분류','범주 예측','지도학습, 카테고리'],
['trending-up','regression','회귀','수치 예측','지도학습, 추세'],
['group','clustering','군집화','그룹 나누기','비지도학습, K-means'],
['git-branch','decision-tree','의사결정트리','트리 기반 분류','분류, 예측 모델'],
['trees','random-forest','랜덤포레스트','앙상블 학습','다수결, 정확도'],
['circle-alert','overfitting','과적합','과도한 학습','모델 일반화, 검증'],
['percent','accuracy','정확도','예측 정확도','모델 평가, 성능'],
['grid-2x2','confusion-matrix','혼동행렬','예측 결과표','분류 평가, TP/FP'],
['trending-down','loss-function','손실함수','오차 측정','모델 학습, 최적화'],
['mountain','gradient-descent','경사하강법','최적값 탐색','학습 알고리즘, 최적화'],
['bot','chatbot','챗봇','대화형 AI','NLP, 고객 서비스'],
['message-square','nlp','자연어처리','텍스트 AI','NLP, 언어 분석'],
['heart','sentiment','감성분석','감정 판별','텍스트 분석, 여론'],
['image','image-recognition','이미지인식','영상 분류','컴퓨터비전, CNN'],
['scan-eye','object-detection','객체탐지','물체 인식','컴퓨터비전, YOLO'],
['sparkles','recommendation','추천시스템','맞춤 추천','협업 필터링, 개인화'],
['wand-sparkles','prompt','프롬프트','AI 지시문','프롬프트 엔지니어링, LLM'],
['bot-message-square','llm','대규모언어모델','LLM AI','GPT, 생성형 AI'],
['braces','embedding','임베딩','벡터 표현','텍스트 벡터화, 의미'],
['split','tokenizer','토크나이저','텍스트 분할','텍스트 전처리, NLP'],
['repeat-2','transfer-learning','전이학습','사전 학습 활용','파인튜닝, 효율'],
['gamepad','reinforcement','강화학습','보상 기반 학습','에이전트, 게임 AI'],
['eye','computer-vision','컴퓨터비전','영상 처리 AI','이미지, 영상 분석'],
['mic','speech-recognition','음성인식','말소리 인식','STT, 음성 AI'],
['volume','text-to-speech','음성합성','텍스트 읽기','TTS, 접근성'],
['bar-chart-2','data-viz','데이터시각화','그래프 표현','차트, 인포그래픽'],
['trending-up-down','correlation','상관관계','변수 간 관계','통계, 분석'],
['activity','distribution','분포','데이터 분포','정규분포, 통계'],
['calculator','statistics','통계','데이터 통계','평균, 중앙값, 표준편차'],
['test-tube','hypothesis','가설검증','통계적 검증','p값, 유의성 검정'],
['users','sample','표본','데이터 표본','표본추출, 모집단'],
['scale','bias-fairness','공정성','AI 편향 방지','윤리, 공정한 AI'],
['shield-check','ai-ethics','AI윤리','인공지능 윤리','책임감 있는 AI'],
['help-circle','explainable-ai','설명가능AI','AI 판단 해석','XAI, 투명성'],
['cpu','model-deploy','모델배포','AI 서비스화','서빙, API 배포'],
['smartphone','edge-ai','엣지AI','기기 내 AI','TinyML, 경량화'],
['sparkle','generative-ai','생성형AI','콘텐츠 생성 AI','이미지/텍스트 생성, GPT'],
['file-pie-chart','data-report','데이터리포트','데이터 보고서','리포트, 분석 결과'],
['presentation-analytics','analytics','분석리포트','분석 프레젠테이션','데이터 발표, 인사이트'],
['funnel','data-funnel','데이터퍼널','단계별 필터','전환율, 깔때기 분석'],
['file-chart','file-chart','차트파일','차트 문서','데이터 시각화 파일'],
['gallery-thumbnails','image-dataset','이미지데이터','이미지 데이터셋','컴퓨터비전, 학습 데이터'],
['audio-lines','audio-data','오디오데이터','음성 데이터','음성 데이터셋, 오디오 AI'],
['audio-waveform','waveform','파형','음파 파형','음성 분석, 신호 처리'],
['file-search','data-discovery','데이터탐색','데이터 발견','탐색적 분석, EDA'],
['database-search','db-search','DB검색','데이터베이스 검색','SQL 쿼리, 데이터 조회'],
['database-backup','db-backup-ai','DB백업','데이터 백업','데이터 보관, 아카이브'],
['table-2','data-table','데이터테이블','데이터 테이블','구조화 데이터, 행열'],
['grid-3x3','feature-matrix','피처행렬','특성 행렬','특성 공학, 데이터 변환'],
['flower','flower-data','꽃데이터','아이리스 데이터','붓꽃 데이터셋, 예제 데이터'],
['orbit','model-orbit','모델궤도','학습 사이클','학습 루프, 에포크'],
['file-badge-2','data-badge','데이터뱃지','데이터 인증','데이터 품질, 검증'],
['sigma','sigma-stat','시그마통계','합계 통계','통계 합산, 시그마'],
['infinity','infinite-data','무한데이터','빅데이터','대용량 데이터, 스트리밍'],
['crown','top-result','최고결과','최상위 결과','순위, 최적 모델'],
],
'07-design-thinking': [
['heart','empathize','공감','사용자 이해','공감 단계, 사용자 중심'],
['crosshair','define','정의','문제 정의','핵심 문제 도출, HMW'],
['lightbulb','ideate','아이디어','발산적 사고','아이디어 생성, 브레인스토밍'],
['box','prototype','프로토타입','시제품 제작','빠른 제작, 검증용'],
['flask-conical','test','테스트','사용자 검증','피드백, 반복 개선'],
['refresh-ccw','iterate','반복개선','지속적 개선','피드백 반영, 발전'],
['sticky-note','sticky-note','포스트잇','메모 포스트잇','아이디어 기록, 분류'],
['users','interview','인터뷰','사용자 면담','사용자 조사, 공감'],
['user','persona','페르소나','대표 사용자','사용자 모델링, 대상 정의'],
['route','journey-map','여정지도','사용자 경험 흐름','고객 여정, 접점 분석'],
['cloud','brainstorm','브레인스토밍','자유 발상','아이디어 발산, 그룹 활동'],
['git-branch','mind-map','마인드맵','방사형 사고 지도','사고 정리, 연결'],
['pen-tool','sketch','스케치','빠른 그림','아이디어 시각화, 초안'],
['layout-template','wireframe','와이어프레임','화면 설계도','UI 설계, 구조'],
['workflow','user-flow','사용자흐름','이용 과정도','화면 전환, UX 설계'],
['film','storyboard','스토리보드','장면 구성표','서비스 시나리오, 영상'],
['clipboard-list','scenario','시나리오','사용 상황 서술','맥락 설계, 상황 묘사'],
['search','observation','관찰','현장 관찰','필드리서치, 발견'],
['zap','insight','인사이트','핵심 발견','통찰, 핵심 파악'],
['grid-3x3','affinity','친화도분류','데이터 그룹화','유사성 분류, 패턴'],
['message-circle','feedback','피드백','반응 수집','사용자 의견, 개선점'],
['thumbs-up','vote','투표','의사 결정','우선순위, 합의'],
['sliders-horizontal','prioritize','우선순위','중요도 결정','영향도-노력도, 선택'],
['timer','sprint','스프린트','집중 작업 기간','디자인 스프린트, 시간제한'],
['presentation','workshop','워크숍','참여형 활동','그룹 활동, 퍼실리테이션'],
['clock','timeboxing','타임박싱','시간 제한 활동','집중, 효율적 진행'],
['smile','icebreaker','아이스브레이커','분위기 조성','팀빌딩, 긴장 완화'],
['users','co-creation','공동창작','함께 만들기','협업, 참여 디자인'],
['arrow-right-left','diverge-converge','발산수렴','확장과 집중','더블다이아몬드, 사고'],
['lock','constraint','제약조건','디자인 제약','한계, 창의적 도전'],
['rocket','mvp','MVP','최소 기능 제품','핵심 기능, 빠른 검증'],
['corner-up-left','pivot','피벗','방향 전환','전략 수정, 적응'],
['map','service-blueprint','서비스설계','서비스 청사진','프론트/백스테이지'],
['compass','value-proposition','가치제안','핵심 가치 제시','사용자 가치, 차별화'],
['alert-circle','pain-point','불편사항','사용자 고충','문제 발견, 개선 기회'],
['check-circle','solution-fit','해결적합성','문제-해결 매칭','솔루션 검증, 적합도'],
['trophy','design-challenge','디자인챌린지','설계 과제','프로젝트 주제, 미션'],
['message-circle-question','hmw','HMW질문','어떻게 하면 좋을까','문제 재정의, 기회 발견'],
['sparkles','creative','창의적사고','창의적 발상','창의성, 혁신'],
['hand-helping','hand-helping','도움','상호 도움','공감 행동, 협력'],
['handshake','handshake','악수','합의 표시','협업, 파트너십'],
['eye','empathy-eye','공감눈','관찰의 눈','사용자 관찰, 공감'],
['ear','empathy-ear','경청','듣기','사용자 인터뷰, 경청'],
['puzzle','puzzle-solve','퍼즐','문제 조각','문제 분해, 솔루션 조합'],
['frame','frame','프레임','작업 프레임','프레임워크, 구조화'],
['gallery-horizontal','gallery','갤러리','작품 전시','포트폴리오, 결과물 전시'],
['ribbon','ribbon','리본','우수 표시','수상, 우수 디자인'],
['crown','crown','왕관','최고 표시','베스트 아이디어, 선정'],
['stamp','stamp','도장','승인 표시','승인, 검증 완료'],
['scan-eye','user-test','사용자테스트','사용성 검증','유저빌리티, 테스트'],
['book-open-check','validation','검증','가설 검증','아이디어 검증, 실험'],
['thumbs-down','negative','부정','부정적 피드백','개선점, 비판적 사고'],
['heart-handshake','empathy-connect','공감연결','감정 연결','라포, 신뢰 구축'],
['blend','blend-idea','아이디어융합','아이디어 결합','융합, 하이브리드'],
['paintbrush','design-brush','디자인붓','디자인 도구','시각 디자인, 표현'],
['palette','design-palette','디자인팔레트','색상 선택','컬러 디자인, 무드보드'],
['circle-check','done','완료','완료 표시','과정 완료, 체크'],
],
'08-steam': [
['microscope','microscope','현미경','미세 관찰 도구','과학 실험, 생물 관찰'],
['test-tube','test-tube','시험관','화학 실험 용기','과학 실험, 화학'],
['beaker','beaker','비커','실험용 비커','과학 실험, 측정'],
['atom','atom','원자','물질의 기본 단위','화학, 원자 구조'],
['dna','dna','DNA','유전 정보 구조','생물, 유전학'],
['flask-conical','flask','플라스크','실험용 플라스크','화학 실험, 반응'],
['thermometer','thermometer','온도계','온도 측정기','과학 실험, 열'],
['magnet','magnet','자석','자기력 도구','물리, 전자기'],
['zap','electricity','전기','전기 에너지','물리, 전자공학'],
['waves','wave','파동','에너지 전달','물리, 소리/빛'],
['sun','solar','태양','태양 에너지','태양계, 에너지'],
['telescope','telescope','망원경','천체 관측','천문학, 우주 탐구'],
['leaf','ecosystem','생태계','생물 환경 시스템','생물, 환경 과학'],
['sprout','plant-growth','식물성장','식물 생장','생물, 생명 과학'],
['droplets','water-cycle','물순환','물의 순환','지구과학, 환경'],
['cloud-rain','weather','기상','날씨 현상','지구과학, 기상 관측'],
['calculator','calculator','계산기','수학 연산 도구','수학, 계산'],
['sigma','sigma','시그마','합계 기호','수학, 통계'],
['pi-square','pi','파이','원주율 기호','수학, 기하'],
['triangle','triangle','삼각형','기하학 도형','수학, 도형'],
['circle','circle-shape','원','원형 도형','수학, 기하'],
['square','square-shape','정사각형','사각형 도형','수학, 도형'],
['hexagon','hexagon','육각형','6각형 도형','수학, 테셀레이션'],
['ruler','ruler','자','길이 측정 도구','수학, 측정'],
['drafting-compass','compass-draw','컴퍼스','원 그리기 도구','수학, 작도'],
['percent','percentage','백분율','비율 표현','수학, 통계'],
['dice-3','probability','확률','사건의 가능성','수학, 확률통계'],
['chart-bar','statistics-chart','통계그래프','통계 시각화','수학, 데이터 분석'],
['axis-3d','coordinate','좌표','좌표계','수학, 공간'],
['trending-up','function-graph','함수그래프','함수 시각화','수학, 함수'],
['globe','geography','지리','지리 정보','사회, 세계 탐구'],
['map','map','지도','위치 정보','사회, 지리'],
['landmark','landmark','랜드마크','역사적 건축물','사회, 문화유산'],
['scroll-text','history','역사','역사 기록','사회, 역사 탐구'],
['users','community','공동체','사회 공동체','사회, 시민 의식'],
['banknote','economy','경제','경제 활동','사회, 경제 교육'],
['scale','justice','정의','공정한 판단','사회, 윤리'],
['palette','art-palette','팔레트','미술 도구','미술, 색채'],
['paintbrush','paintbrush','붓','그림 도구','미술, 표현 활동'],
['image','artwork','작품','예술 작품','미술, 감상'],
['pen-tool','drawing','드로잉','그리기','미술, 소묘'],
['blend','color-mixing','색혼합','색 섞기','미술, 색채 이론'],
['music','music-note','음표','음악 기호','음악, 음악 수업'],
['music-4','melody','멜로디','음악 선율','음악, 작곡'],
['headphones','listening','감상','음악 감상','음악, 감상 활동'],
['video','film-making','영상제작','영상 콘텐츠','미디어, 영상 편집'],
['camera','photography','사진','사진 촬영','미술, 사진 표현'],
['drama','theater','연극','공연 예술','예술, 표현 활동'],
['scissors','craft','공예','만들기 활동','미술, 수공예'],
['origami','origami','종이접기','종이 조형','미술, 조형 활동'],
['type','typography','타이포그래피','글자 디자인','디자인, 글꼴'],
['pipette','color-theory','색채이론','색의 원리','미술, 색 조합'],
['grid-3x3','composition','구성','화면 구성','미술, 디자인 원리'],
['move-3d','perspective','원근법','깊이 표현','미술, 공간 표현'],
['copy','pattern','패턴','반복 무늬','수학+미술, 테셀레이션'],
['rotate-cw','symmetry','대칭','좌우 대칭','수학+미술, 기하'],
['recycle','sustainability','지속가능성','지속가능한 발전','환경, 에코디자인'],
['trees','environment','환경','자연 환경','과학, 환경 보호'],
['solar-panel','renewable','신재생에너지','친환경 에너지','과학+사회, 에너지'],
['earth','earth-science','지구과학','지구 탐구','과학, 지질/기상'],
['flask-round','flask-round','둥근플라스크','둥근바닥 플라스크','화학 실험, 증류'],
['test-tube-2','test-tube-2','시험관2','시험관 세트','비교 실험, 대조군'],
['test-tube-diagonal','test-tube-diag','기울인시험관','기울어진 시험관','반응 관찰, 실험'],
['pipette','pipette','피펫','소량 측정 도구','정밀 측정, 화학'],
['orbit','orbit-steam','궤도','행성 궤도','천문학, 태양계'],
['satellite','satellite','인공위성','궤도 위성','우주 탐사, 통신'],
['clover','clover','클로버','네잎클로버','식물, 생물 분류'],
['flower','flower','꽃','꽃 식물','식물 구조, 생물'],
['flower-2','flower-2','꽃2','다른 꽃 형태','꽃 종류, 식물 다양성'],
['apple','apple','사과','과일','식물 열매, 만유인력'],
['egg','egg','달걀','동물 알','생물, 발생학'],
['fish','fish','물고기','어류','생물 분류, 수생 생물'],
['mountain','mountain','산','산 지형','지구과학, 지형'],
['rainbow','rainbow','무지개','빛의 스펙트럼','물리, 빛의 분산'],
['sunrise','sunrise','일출','해 뜨기','천문, 자전'],
['sunset','sunset','일몰','해 지기','천문, 자전'],
['moon-star','moon-star','달별','달과 별','천문학, 야간 관찰'],
['wind','wind-steam','바람','대기 흐름','기상, 바람의 방향'],
['tornado','tornado','토네이도','회오리바람','기상 현상, 자연재해'],
['cloud-sun','cloud-sun','구름해','구름과 태양','기상, 날씨 변화'],
['diamond','diamond-shape','다이아몬드','마름모 도형','수학, 도형'],
['pentagon','pentagon','오각형','5각형 도형','수학, 정다각형'],
['octagon','octagon','팔각형','8각형 도형','수학, 정다각형'],
['cone','cone-shape','원뿔','원뿔 도형','수학, 입체도형'],
['cylinder','cylinder-shape','원기둥','원기둥 도형','수학, 입체도형'],
['cube','cube-shape','정육면체','큐브 도형','수학, 입체도형'],
['sphere','sphere-shape','구','구 도형','수학, 입체도형'],
['prism','prism-shape','프리즘','삼각기둥','수학, 입체도형/빛의 굴절'],
['prism-light','prism-light','프리즘빛','빛의 분산','물리, 스펙트럼'],
['hexagonal-prism','hex-prism','육각기둥','6각 기둥','수학, 입체도형'],
['pyramid','pyramid-shape','사각뿔','피라미드 도형','수학, 입체도형'],
['cuboid','cuboid','직육면체','직육면체 도형','수학, 입체도형'],
['torus','torus','원환체','도넛 형태','수학, 고급 입체도형'],
['hemisphere','hemisphere','반구','반구 도형','수학, 입체도형'],
['cube-3d-sphere','cube-sphere','구와정육면체','외접/내접 도형','수학, 기하학 관계'],
['guitar','guitar','기타','현악기','음악, 악기'],
['piano','piano','피아노','건반악기','음악, 악기'],
['music-2','music-2','음악2','음악 기호','음악, 리듬'],
['audio-lines','audio-lines','오디오선','음파 시각화','음악, 소리 분석'],
['frame','art-frame','액자','그림 액자','미술, 전시'],
['spray-can','spray','스프레이','스프레이 도구','미술, 그래피티'],
['paint-bucket','paint-bucket','페인트통','채색 도구','미술, 채색'],
['paint-roller','paint-roller','롤러','페인트 롤러','미술, 넓은 면 채색'],
['brush','brush','솔','붓 도구','미술, 수채화'],
['stamp','stamp-art','도장','판화 도구','미술, 판화'],
['wheat','wheat','밀','곡물','농업, 식물'],
['grape','grape','포도','과일','식물, 포도원'],
['citrus','citrus','감귤','감귤류','식물, 비타민'],
],
'09-teaching': [
['book-open','textbook','교과서','수업 교재','교과 학습, 교재 활용'],
['notebook-pen','notebook','공책','필기 노트','학습 기록, 필기'],
['pencil','pencil','연필','필기 도구','학습, 필기'],
['presentation','whiteboard','화이트보드','수업 판서','강의, 설명'],
['school','school','학교','교육 기관','학교 생활, 교육'],
['bell','school-bell','학교종','수업 시작/종료','학교 일과, 시간 관리'],
['calendar','schedule','시간표','수업 일정','학사 일정, 계획'],
['clipboard-list','assignment','과제','학습 과제','과제 제출, 평가'],
['file-text','exam','시험','평가 시험지','중간/기말, 평가'],
['file-check','report-card','성적표','학업 성적','성적 평가, 피드백'],
['star','grade-star','등급별','학업 등급','성취도, 평가 결과'],
['grid-3x3','rubric','루브릭','평가 기준표','수행평가, 채점 기준'],
['list-checks','checklist','체크리스트','점검 목록','자기 점검, 평가'],
['circle-check','self-assessment','자기평가','스스로 평가','메타인지, 성찰'],
['users','peer-review','동료평가','상호 평가','협력 학습, 피드백'],
['folder','portfolio','포트폴리오','학습 성과물','종합 평가, 성장 기록'],
['target','learning-goal','학습목표','수업 목표','성취기준, 수업 설계'],
['book','curriculum','교육과정','교과 체계','교육과정, 핵심역량'],
['file-text','lesson-plan','수업안','수업 지도안','수업 설계, 교수법'],
['layers','scaffolding','비계','학습 지원 단계','단계적 지원, 수준별'],
['pyramid','bloom','블룸분류','사고력 위계','인지 수준, 평가 설계'],
['users-round','group-work','모둠활동','소그룹 협업','협력 학습, 토의'],
['user-round','individual','개별활동','개인 학습','자기주도, 개별화'],
['message-circle','discussion','토론','의견 교환','토의토론, 비판적 사고'],
['megaphone','presentation-teach','발표','학습 발표','표현력, 의사소통'],
['help-circle','inquiry','탐구','질문과 조사','탐구 학습, 호기심'],
['lightbulb','project-based','프로젝트학습','프로젝트 수업','PBL, 실생활 문제'],
['rotate-ccw','flipped','거꾸로수업','사전학습 후 활동','플립드 러닝, 자기주도'],
['monitor','online-class','온라인수업','원격 학습','이러닝, 디지털 수업'],
['video','video-lesson','영상수업','교육 영상','동영상 강의, 콘텐츠'],
['layout-dashboard','lms','LMS','학습관리시스템','구글클래스룸, 온라인 관리'],
['award','certificate','수료증','이수 인증서','인증, 수료'],
['trophy','trophy','트로피','수상 트로피','시상, 동기부여'],
['medal','medal','메달','성취 메달','포상, 인정'],
['trending-up','progress','학습진도','학습 진행률','진도 관리, 성장'],
['bar-chart-2','achievement','성취도','학습 달성률','평가, 성취 수준'],
['smile','engagement','참여도','학습 참여','동기부여, 적극성'],
['brain','metacognition','메타인지','학습 자각','자기 점검, 사고력'],
['compass','guidance','진로지도','진로 안내','진로 탐색, 상담'],
['graduation-cap','graduation','졸업','학업 완료','졸업, 성장'],
['school-2','school-2','학교2','교육 건물','학교, 캠퍼스'],
['university','university','대학교','고등 교육 기관','대학, 진학'],
['backpack','backpack','책가방','학생 가방','등교, 학용품'],
['briefcase','briefcase','서류가방','교사 가방','교사, 업무 자료'],
['book-check','book-check','교재확인','학습 완료 교재','학습 완료, 체크'],
['book-copy','book-copy','교재복사','교재 복제','유인물, 자료 배포'],
['book-open-text','book-text','교재내용','교재 텍스트','읽기, 교재 학습'],
['book-type','book-type','교재유형','교재 종류','교재 분류, 유형별'],
['book-user','book-student','학생교재','학생용 교재','학생 자료, 개별 학습'],
['notebook-tabs','notebook-tabs','탭노트','색인 노트','정리, 과목별 분류'],
['pen','pen','펜','필기용 펜','학습, 기록'],
['highlighter','highlighter','형광펜','강조 펜','핵심 표시, 밑줄'],
['eraser','eraser','지우개','수정 도구','수정, 오답 수정'],
['ruler','ruler-teach','자','측정 도구','수학, 기하 작도'],
['book-open-check','reading-done','읽기완료','독서 완료','읽기 학습, 독서록'],
['library','library','도서관','학교 도서관','자료 검색, 독서'],
['speech','speaking','말하기','구두 발표','의사소통, 스피치'],
['podcast','edu-podcast','교육팟캐스트','교육 방송','오디오 학습, 콘텐츠'],
['creative-commons','open-edu','오픈교육','공개 교육 자원','OER, 무료 교육자료'],
['clock','timer-teach','수업타이머','시간 관리','수업 시간, 타이머'],
['kanban','learning-board','학습보드','학습 현황판','학습 관리, 진도'],
['flame','passion','열정','학습 열정','동기부여, 도전'],
['thumbs-up','praise','칭찬','긍정 평가','격려, 칭찬'],
['hand-helping','support','지원','학습 도움','도움, 보조'],
],
'10-visual-symbols': [
['arrow-right','arrow-right','오른쪽화살표','진행 방향','다음 단계, 흐름 표시'],
['arrow-left','arrow-left','왼쪽화살표','이전 방향','되돌아가기, 이전 단계'],
['arrow-up','arrow-up','위쪽화살표','상승 방향','증가, 향상'],
['arrow-down','arrow-down','아래쪽화살표','하강 방향','감소, 다운로드'],
['arrow-left-right','arrow-bidirectional','양방향화살표','상호 교환','비교, 상호작용'],
['corner-down-right','arrow-curved','곡선화살표','방향 전환','전환, 이동'],
['maximize-2','expand','확장','크기 확장','확대, 펼치기'],
['minimize-2','collapse','축소','크기 축소','줄이기, 접기'],
['check','checkmark','체크','완료 표시','완료, 정답'],
['x','cross','엑스','취소/오답 표시','오답, 취소, 삭제'],
['plus','plus-sign','더하기','추가 기호','추가, 새로 만들기'],
['minus','minus-sign','빼기','제거 기호','제거, 축소'],
['circle-help','question','물음표','의문 표시','질문, 도움말'],
['circle-alert','exclamation','느낌표','주의 표시','강조, 중요'],
['info','info','정보','안내 표시','참고, 정보 제공'],
['alert-triangle','warning','경고삼각','위험 경고','주의, 경고'],
['alert-octagon','error-sign','에러표시','오류 발생','에러, 문제 발생'],
['badge-check','success','성공뱃지','완료 인증','성공, 달성'],
['star','star','별표','중요/평점 표시','즐겨찾기, 평가'],
['heart','heart','하트','좋아요/관심','좋아요, 감정 표현'],
['bookmark','bookmark','북마크','페이지 표시','저장, 중요 표시'],
['flag','flag','깃발','표시/신고','신고, 마일스톤'],
['clock','clock','시계','시간 표시','시간, 마감'],
['calendar','calendar','달력','날짜 표시','일정, 날짜'],
['search','search','검색','찾기 기능','검색, 탐색'],
['filter','filter','필터','조건 걸기','분류, 조건 선택'],
['arrow-up-down','sort','정렬','순서 정리','오름차순/내림차순'],
['refresh-cw','refresh','새로고침','다시 불러오기','갱신, 재시도'],
['link','link','링크','연결 표시','하이퍼링크, 참조'],
['unlink','unlink','링크해제','연결 끊기','연결 해제'],
['lock','lock','잠금','보안 잠금','보안, 접근 제한'],
['unlock','unlock','잠금해제','보안 해제','해제, 접근 허용'],
['eye','visible','보이기','표시 상태','공개, 확인'],
['eye-off','hidden','숨기기','비표시 상태','비공개, 숨김'],
['bell','notification','알림','알림 표시','알림, 공지'],
['volume-2','volume','소리','음량 표시','소리, 볼륨'],
['volume-x','mute','음소거','소리 끄기','음소거, 무음'],
['play','play','재생','시작 버튼','재생, 시작'],
['pause','pause','일시정지','멈춤 버튼','일시정지, 대기'],
['square','stop-btn','정지','중지 버튼','정지, 종료'],
['skip-forward','forward','다음','앞으로 이동','다음, 건너뛰기'],
['skip-back','backward','이전','뒤로 이동','이전, 되감기'],
['download','download','다운로드','파일 받기','저장, 내려받기'],
['upload','upload','업로드','파일 올리기','제출, 올려보내기'],
['share-2','share','공유','나눔 표시','공유, 배포'],
['copy','copy','복사','복제 기능','복사, 붙여넣기'],
['clipboard','paste','붙여넣기','붙이기 기능','붙여넣기'],
['trash-2','delete','삭제','지우기','삭제, 제거'],
['pencil','edit','편집','수정 기능','수정, 편집'],
['settings','settings','설정','환경 설정','설정, 옵션'],
['home','home','홈','첫 화면','메인, 시작점'],
['user','user','사용자','개인 프로필','프로필, 계정'],
['users','group','그룹','다수 사용자','팀, 그룹'],
['mail','mail','메일','전자 우편','이메일, 연락'],
['message-square','chat','채팅','대화창','메시지, 소통'],
['phone','phone','전화','전화 연결','통화, 연락'],
['image','image','이미지','사진/그림','이미지, 시각자료'],
['file','file','파일','문서 파일','문서, 자료'],
['folder','folder','폴더','파일 묶음','분류, 정리'],
['folder-open','folder-open','열린폴더','폴더 열기','파일 탐색, 열기'],
['code','code','코드','프로그래밍 코드','코드, 기술'],
['terminal','terminal-sym','터미널','명령줄','CLI, 개발'],
['database','database-sym','데이터베이스','DB 기호','데이터, 저장'],
['cloud','cloud-sym','클라우드','클라우드 기호','온라인, 저장'],
['wifi','wifi-sym','와이파이','무선 기호','인터넷, 연결'],
['battery-full','battery-sym','배터리','전원 기호','충전, 전원 상태'],
['sun','bright','밝기','밝기 조절','화면, 밝기'],
['moon','dark-mode','다크모드','어두운 화면','다크모드, 테마'],
['accessibility','accessibility','접근성','누구나 사용','유니버설 디자인, 배리어프리'],
['languages','language','언어','다국어 표시','번역, 다국어'],
['circle-dot','number-1','1번','첫 번째','순서, 단계 1'],
['circle-dot','number-2','2번','두 번째','순서, 단계 2'],
['circle-ellipsis','number-3','3번','세 번째','순서, 단계 3'],
['lightbulb','tip','팁','유용한 조언','도움말, 팁 박스'],
['pen-line','note','메모','기록 표시','주석, 참고사항'],
['flag','important','중요','중요 표시','강조, 필수'],
['badge-check','new-badge','신규','새로운 항목','NEW, 최신'],
['flame','hot','인기','인기 항목','HOT, 추천'],
['trending-up','trending-up','상승추세','증가 경향','성장, 개선'],
['trending-down','trending-down','하락추세','감소 경향','감소, 주의'],
['circle-check','circle-check','원체크','원형 확인','확인, 올바름'],
['circle-x','circle-x','원엑스','원형 취소','취소, 틀림'],
['circle-plus','circle-plus','원더하기','원형 추가','추가, 새 항목'],
['circle-minus','circle-minus','원빼기','원형 제거','제거, 감소'],
['circle-pause','circle-pause','원일시정지','원형 멈춤','일시정지, 대기'],
['circle-play','circle-play','원재생','원형 재생','재생, 시작'],
['circle-stop','circle-stop','원정지','원형 중지','정지, 종료'],
['circle-user','circle-user','원사용자','원형 프로필','프로필, 사용자'],
['circle-percent','circle-percent','원퍼센트','원형 비율','비율, 할인'],
['circle-gauge','circle-gauge','원게이지','원형 측정','진행도, 측정'],
['square-check','square-check','사각체크','사각 확인','체크박스, 완료'],
['square-x','square-x','사각엑스','사각 취소','체크박스 해제, 취소'],
['square-plus','square-plus','사각더하기','사각 추가','새로 만들기, 추가'],
['square-minus','square-minus','사각빼기','사각 제거','제거, 축소'],
['square-pen','square-pen','사각편집','사각 수정','편집, 수정'],
['square-user','square-user','사각사용자','사각 프로필','프로필, 계정'],
['octagon','octagon-sym','팔각형','정지 기호','정지, 금지'],
['octagon-alert','octagon-alert','팔각경고','팔각 경고','위험 경고, 주의'],
['triangle-alert','triangle-warn','삼각경고','삼각 주의','경고, 위험'],
['diamond','diamond-sym','다이아','마름모 기호','특별, 프리미엄'],
['diamond-plus','diamond-plus','다이아추가','마름모 추가','특별 추가, 프리미엄'],
['heart-crack','heart-break','깨진하트','상실/아쉬움','아쉬움, 실패'],
['heart-pulse','heart-pulse','하트박동','생동감','활력, 건강'],
['hand-metal','hand-cheer','환호','응원 손짓','응원, 축하'],
['thumbs-up','thumbs-up','엄지위','좋아요 표시','좋아요, 긍정'],
['thumbs-down','thumbs-down','엄지아래','싫어요 표시','싫어요, 부정'],
['undo','undo','되돌리기','이전으로','취소, 실행 취소'],
['redo','redo','다시하기','다음으로','재실행, 앞으로'],
['rotate-ccw','rotate-left','왼회전','반시계 회전','회전, 복원'],
['rotate-cw','rotate-right','오른회전','시계 회전','회전, 진행'],
['flip-horizontal','flip-h','좌우반전','수평 뒤집기','반전, 대칭'],
['flip-vertical','flip-v','상하반전','수직 뒤집기','반전, 대칭'],
['zoom-in','zoom-in','확대','크게 보기','확대, 상세'],
['zoom-out','zoom-out','축소','작게 보기','축소, 전체'],
['grip-horizontal','drag-h','가로드래그','가로 이동','정렬, 이동'],
['grip-vertical','drag-v','세로드래그','세로 이동','정렬, 이동'],
['move','move-sym','이동','위치 이동','이동, 드래그'],
['move-diagonal','move-diag','대각이동','대각선 이동','크기 조절, 리사이즈'],
['bring-to-front','to-front','앞으로','맨 앞으로','레이어, 앞으로 가져오기'],
['send-to-back','to-back','뒤로','맨 뒤로','레이어, 뒤로 보내기'],
],
'11-numbers': [
['number-0','num-0','숫자0','숫자 영','수 세기, 영의 개념'],
['number-1','num-1','숫자1','숫자 일','수 세기, 첫 번째'],
['number-2','num-2','숫자2','숫자 이','수 세기, 두 번째'],
['number-3','num-3','숫자3','숫자 삼','수 세기, 세 번째'],
['number-4','num-4','숫자4','숫자 사','수 세기, 네 번째'],
['number-5','num-5','숫자5','숫자 오','수 세기, 다섯 번째'],
['number-6','num-6','숫자6','숫자 육','수 세기, 여섯 번째'],
['number-7','num-7','숫자7','숫자 칠','수 세기, 일곱 번째'],
['number-8','num-8','숫자8','숫자 팔','수 세기, 여덟 번째'],
['number-9','num-9','숫자9','숫자 구','수 세기, 아홉 번째'],
['number-10','num-10','숫자10','숫자 십','수 세기, 열 번째'],
['number-11','num-11','숫자11','숫자 십일','수 세기, 열한 번째'],
['_num:12','num-12','숫자12','숫자 십이','수 세기, 시계 숫자'],
['_num:13','num-13','숫자13','숫자 십삼','수 세기, 열세 번째'],
['_num:14','num-14','숫자14','숫자 십사','수 세기, 열네 번째'],
['_num:15','num-15','숫자15','숫자 십오','수 세기, 열다섯 번째'],
['_num:16','num-16','숫자16','숫자 십육','16진법, 비트 단위'],
['_num:17','num-17','숫자17','숫자 십칠','수 세기, 열일곱 번째'],
['_num:18','num-18','숫자18','숫자 십팔','수 세기, 열여덟 번째'],
['_num:19','num-19','숫자19','숫자 십구','수 세기, 열아홉 번째'],
['_num:20','num-20','숫자20','숫자 이십','수 세기, 스무 번째'],
['_num:21','num-21','숫자21','숫자 이십일','수 세기, 스물한 번째'],
['_num:22','num-22','숫자22','숫자 이십이','수 세기, 스물두 번째'],
['_num:23','num-23','숫자23','숫자 이십삼','수 세기, 스물세 번째'],
['_num:24','num-24','숫자24','숫자 이십사','수 세기, 24시간'],
['_num:25','num-25','숫자25','숫자 이십오','수 세기, 스물다섯 번째'],
['_num:26','num-26','숫자26','숫자 이십육','알파벳 개수, 26자'],
['_num:27','num-27','숫자27','숫자 이십칠','수 세기, 3의 세제곱'],
['_num:28','num-28','숫자28','숫자 이십팔','수 세기, 완전수'],
['_num:29','num-29','숫자29','숫자 이십구','수 세기, 소수'],
['_num:30','num-30','숫자30','숫자 삼십','수 세기, 서른 번째'],
['_num:31','num-31','숫자31','숫자 삼십일','수 세기, 한 달 일수'],
['_num:32','num-32','숫자32','숫자 삼십이','32비트, 컴퓨터 구조'],
['_num:33','num-33','숫자33','숫자 삼십삼','수 세기, 서른세 번째'],
['_num:34','num-34','숫자34','숫자 삼십사','수 세기, 서른네 번째'],
['_num:35','num-35','숫자35','숫자 삼십오','수 세기, 서른다섯 번째'],
['_num:36','num-36','숫자36','숫자 삼십육','수 세기, 36진법'],
['_num:37','num-37','숫자37','숫자 삼십칠','수 세기, 소수'],
['_num:38','num-38','숫자38','숫자 삼십팔','수 세기, 서른여덟 번째'],
['_num:39','num-39','숫자39','숫자 삼십구','수 세기, 서른아홉 번째'],
['_num:40','num-40','숫자40','숫자 사십','수 세기, 마흔 번째'],
['circle-number-0','circle-num-0','원숫자0','원 안의 0','번호 표시, 순서'],
['circle-number-1','circle-num-1','원숫자1','원 안의 1','번호 표시, 1단계'],
['circle-number-2','circle-num-2','원숫자2','원 안의 2','번호 표시, 2단계'],
['circle-number-3','circle-num-3','원숫자3','원 안의 3','번호 표시, 3단계'],
['circle-number-4','circle-num-4','원숫자4','원 안의 4','번호 표시, 4단계'],
['circle-number-5','circle-num-5','원숫자5','원 안의 5','번호 표시, 5단계'],
['circle-number-6','circle-num-6','원숫자6','원 안의 6','번호 표시, 6단계'],
['circle-number-7','circle-num-7','원숫자7','원 안의 7','번호 표시, 7단계'],
['circle-number-8','circle-num-8','원숫자8','원 안의 8','번호 표시, 8단계'],
['circle-number-9','circle-num-9','원숫자9','원 안의 9','번호 표시, 9단계'],
],
'12-shapes': [
['circle','shape-circle','원','원형','2D 도형, 기본 도형'],
['square','shape-square','정사각형','정사각형 도형','2D 도형, 기본 도형'],
['triangle','shape-triangle','삼각형','삼각형 도형','2D 도형, 기본 도형'],
['rectangle','shape-rectangle','직사각형','직사각형 도형','2D 도형, 사각형'],
['diamond','shape-diamond','마름모','마름모 도형','2D 도형, 사각형'],
['pentagon','shape-pentagon','오각형','정오각형 도형','2D 도형, 정다각형'],
['hexagon','shape-hexagon','육각형','정육각형 도형','2D 도형, 벌집 구조'],
['octagon','shape-octagon','팔각형','정팔각형 도형','2D 도형, 정지 표지'],
['oval','shape-oval','타원','타원형 도형','2D 도형, 행성 궤도'],
['star','shape-star','별','별 모양 도형','2D 도형, 꼭짓점'],
['heart','shape-heart','하트','하트 모양','2D 도형, 대칭 곡선'],
['polygon','shape-polygon','다각형','일반 다각형','2D 도형, n각형'],
['triangle-square-circle','shape-basic','기본도형','원삼각사각','기본 3도형, 분류'],
['circle-triangle','circle-triangle','원삼각','원과 삼각형','도형 관계, 내접/외접'],
['circle-square','circle-square','원사각','원과 사각형','도형 관계, 내접/외접'],
['line','shape-line','직선','선분','기본 요소, 1차원'],
['line-dashed','shape-dashed','점선','점선 형태','보조선, 대칭축'],
['cube','shape-cube','정육면체','큐브','3D 도형, 정다면체'],
['cuboid','shape-cuboid','직육면체','박스 형태','3D 도형, 상자'],
['sphere','shape-sphere','구','구체','3D 도형, 공'],
['hemisphere','shape-hemisphere','반구','반구 형태','3D 도형, 돔'],
['cylinder','shape-cylinder','원기둥','원기둥 형태','3D 도형, 기둥'],
['cone','shape-cone','원뿔','원뿔 형태','3D 도형, 뿔'],
['pyramid','shape-pyramid','사각뿔','피라미드 형태','3D 도형, 뿔'],
['prism','shape-prism','삼각기둥','프리즘 형태','3D 도형, 기둥'],
['hexagonal-prism','shape-hex-prism','육각기둥','육각 기둥 형태','3D 도형, 기둥'],
['torus','shape-torus','원환체','도넛 형태','3D 도형, 고급'],
['cube-3d-sphere','shape-inscribed','내접외접','구와 정육면체 관계','3D 도형 관계, 기하'],
['prism-light','shape-prism-light','프리즘빛','빛의 굴절 프리즘','3D 도형, 광학'],
['rotate-3d','shape-3d-rotate','3D회전','입체 회전','3D 변환, 회전'],
['box-model','shape-box-model','박스모델','상자 모델','CSS 박스모델, 3D 분해'],
['dimensions','shape-dimensions','치수','크기 표시','측정, 길이/너비/높이'],
['aspect-ratio','shape-ratio','가로세로비','비율 표시','비율, 화면 비율'],
],
};

// 커스텀 숫자 SVG 생성 (12~40처럼 Tabler에 없는 숫자용)
function generateNumberSvg(num, category, idx) {
  const p = PALETTES[category];
  const uid = `g${idx}`;
  const [g0, g1] = p.grad[idx % 2];
  const ac = p.accent[(idx + 2) % p.accent.length];
  const numStr = String(num);
  const fontSize = numStr.length <= 2 ? 16 : 13;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none">
  <defs>
    <linearGradient id="${uid}" x1="0" y1="0" x2="64" y2="64" gradientUnits="userSpaceOnUse">
      <stop offset="0%" stop-color="${g0}"/>
      <stop offset="100%" stop-color="${g1}"/>
    </linearGradient>
  </defs>
  <rect x="4" y="4" width="56" height="56" rx="16" fill="${p.bg}"/>
  <rect x="4" y="4" width="56" height="56" rx="16" fill="none" stroke="${ac}" stroke-width="1" opacity="0.15"/>
  <text x="32" y="33" text-anchor="middle" dominant-baseline="central" font-family="system-ui,-apple-system,sans-serif" font-weight="700" font-size="${fontSize}" fill="url(#${uid})">${numStr}</text>
</svg>`;
}

function transformSvg(content, category, idx) {
  const p = PALETTES[category];
  const inner = content.match(/<svg[^>]*>([\s\S]*?)<\/svg>/);
  if (!inner) return null;
  let body = inner[1].replace(/<!--[\s\S]*?-->/g, '').trim();
  const uid = `g${idx}`;
  const [g0, g1] = p.grad[idx % 2];
  const ac = p.accent[(idx + 2) % p.accent.length];
  body = body.replace(/stroke="currentColor"/g, `stroke="url(#${uid})"`);
  body = body.replace(/fill="currentColor"/g, `fill="url(#${uid})"`);
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" fill="none">
  <defs>
    <linearGradient id="${uid}" x1="0" y1="0" x2="64" y2="64" gradientUnits="userSpaceOnUse">
      <stop offset="0%" stop-color="${g0}"/>
      <stop offset="100%" stop-color="${g1}"/>
    </linearGradient>
  </defs>
  <rect x="4" y="4" width="56" height="56" rx="16" fill="${p.bg}"/>
  <rect x="4" y="4" width="56" height="56" rx="16" fill="none" stroke="${ac}" stroke-width="1" opacity="0.15"/>
  <g transform="translate(14,14) scale(1.5)" stroke="url(#${uid})" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" fill="none">
${body}
  </g>
</svg>`;
}

// 카탈로그도 함께 생성
const catalog = { version: '1.0.0', generatedAt: new Date().toISOString().split('T')[0], categories: [], icons: [] };
let total = 0, failed = 0;

for (const [cat, icons] of Object.entries(ICONS)) {
  const dir = path.join(SVG, cat);
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });

  const catName = { '01-devices':'컴퓨터와 디지털 기기','02-physical-computing':'피지컬컴퓨팅과 메이킹','03-programming':'소프트웨어와 프로그래밍','04-algorithm':'알고리즘과 자료구조','05-network-security':'네트워크와 정보보안','06-data-ai':'데이터와 인공지능','07-design-thinking':'디자인씽킹과 문제해결','08-steam':'STEAM 융합','09-teaching':'수업 활동과 평가','10-visual-symbols':'시각 기호와 안내 요소','11-numbers':'숫자와 번호','12-shapes':'도형과 입체' }[cat] || cat;

  catalog.categories.push({ id: cat, name: catName, count: icons.length, color: PALETTES[cat].grad[0][0] });

  icons.forEach((icon, idx) => {
    const [iconName, filename, name, desc, useCases] = icon;

    // 커스텀 숫자 아이콘 처리 (_num:12 형식)
    if (iconName.startsWith('_num:')) {
      const num = parseInt(iconName.split(':')[1], 10);
      const result = generateNumberSvg(num, cat, idx);
      fs.writeFileSync(path.join(dir, `${filename}.svg`), result);
      catalog.icons.push({ filename: `${filename}.svg`, category: cat, name, description: desc, tags: desc.split(/[, ]+/), useCases, source: 'custom' });
      total++;
      return;
    }

    // Lucide 먼저, 없으면 Tabler에서 탐색
    let src = path.join(LUCIDE, `${iconName}.svg`);
    let source = 'lucide';
    if (!fs.existsSync(src)) {
      src = path.join(TABLER, `${iconName}.svg`);
      source = 'tabler';
    }
    if (!fs.existsSync(src)) {
      console.error(`MISSING: ${iconName}.svg (for ${filename})`);
      failed++;
      return;
    }
    const content = fs.readFileSync(src, 'utf-8');
    const result = transformSvg(content, cat, idx);
    if (result) {
      fs.writeFileSync(path.join(dir, `${filename}.svg`), result);
      catalog.icons.push({ filename: `${filename}.svg`, category: cat, name, description: desc, tags: desc.split(/[, ]+/), useCases, source });
      total++;
    } else { failed++; }
  });
  console.log(`✓ ${cat}: ${icons.length}`);
}

catalog.totalCount = total;
fs.writeFileSync(path.join(__dirname, '..', 'catalog.json'), JSON.stringify(catalog, null, 2), 'utf-8');

// CSV 생성
const csvHeader = '파일명,카테고리,이미지이름,이미지설명,사용하면좋을상황';
const csvRows = catalog.icons.map(i => `${i.filename},${i.category},${i.name},${i.description},${i.useCases}`);
fs.writeFileSync(path.join(__dirname, '..', 'catalog.csv'), '\uFEFF' + csvHeader + '\n' + csvRows.join('\n'), 'utf-8');

console.log(`\nDone! ${total} generated, ${failed} failed`);
console.log(`catalog.json: ${catalog.icons.length} entries`);
console.log(`catalog.csv: ${csvRows.length} rows`);
